---
- name: Ensure git is installed
  apt: pkg=git
- name: Ensure that deploy owns /var/www
  file: owner=deploy group=deploy path=/var/www
- name: Generate the apache config for the app
  template: src=default
            dest=/etc/apache2/sites-available/default
  notify: Restart Apache
- name: Ensure that .env exists (but will need to be filled in by hand)
  file: path=/var/www/shared/.env owner=deploy group=deploy state=touch
