---
# TODO Ensure that deploy user is setup first
# TODO Ensure that apache is setup first
- name: Ensure git is installed
  apt: pkg=git
- name: Ensure that deploy owns /var/www
  file: owner=deploy group=deploy path=/var/www
- name: Ensure that /etc/apache2/ssl exists
  file: path=/etc/apache2/ssl mode=0700 state=directory
- name: Add SSL certificate (CA)
  copy: src=ssl/ca.pem dest=/etc/apache2/ssl/ca.pem mode=0600
  notify: Restart Apache
- name: Add SSL certificate (public)
  copy: src=ssl/ssl.crt dest=/etc/apache2/ssl/ssl.crt mode=0600
  notify: Restart Apache
- name: Add SSL certificate (private)
  copy: src=ssl/ssl.key.secure dest=/etc/apache2/ssl/ssl.key mode=0600
  notify: Restart Apache
- name: Add SSL certificate (class 1)
  copy: src=ssl/sub.class1.server.ca.pem dest=/etc/apache2/ssl/sub.class1.server.ca.pem mode=0600
  notify: Restart Apache
# TODO Don't need to restart. reload would be fine.
- name: Generate the apache config for the app
  template: src=default
            dest=/etc/apache2/sites-available/default
  notify: Restart Apache
- name: Generate the apache config for morph.io
  template: src=morph.io
            dest=/etc/apache2/sites-available/morph.io
  notify: Restart Apache
- name: Ensure that morph.io is enabled
  command: a2ensite morph.io creates=/etc/apache2/sites-enabled/morph.io
  notify: Restart Apache
- name: Switch on Apache SSL support
  command: a2enmod ssl creates=/etc/apache2/mods-enabled/ssl.load
  notify: Restart Apache
- name: Ensure that /var/www/shared exists
  file: path=/var/www/shared owner=deploy group=deploy state=directory
- name: Ensure that .env exists
  copy: src=../{{ env_file }} dest=/var/www/shared/.env owner=deploy group=deploy
# TODO This is a nasty hack. Would be much nicer to do this in the capistrano
# deploy. But security concerns (the need for passwordless sudo) make this hard.
- name: Install foreman
  gem: name=foreman state=present user_install=no
- name: Ensure Procfile.production copied
  copy: src=../Procfile.production dest=/home/deploy/Procfile.production
# TODO Restart morph service if this changed the /etc/init files
- name: Ensure upstart is setup for the application
  command: foreman export upstart /etc/init -u deploy -a morph -f /home/deploy/Procfile.production --root /var/www/current
- name: Create sudoers ready for testing
  template: src=sudoers dest=/etc/sudoers.d/deploy.test owner=root group=root mode=0440
- name: Test sudoers
  command: visudo -c -f /etc/sudoers.d/deploy.test
- name: Make sudoers live
  command: mv -f /etc/sudoers.d/deploy.test /etc/sudoers.d/deploy
# TODO There are serious security concerns with doing this. This will probably be improved
# as Docker matures
- name: Add deploy to the docker group (so it has permissions to do dockery things)
  user: name=deploy groups=docker
- name: Install dependency for following command
  apt: pkg=python-mysqldb
- name: Create database
  mysql_db: name=morph
- name: Create directory /var/www/shared/config
  file: path=/var/www/shared/config owner=deploy group=deploy state=directory
- name: Copy over database configuration for application
  template: src=database.yml dest=/var/www/shared/config/database.yml owner=deploy group=deploy
- name: Dependency for following command
  apt: pkg=python-passlib
- name: Add basic authentication password
  htpasswd: path=/var/www/shared/htpasswd name=test password=test owner=root group=www-data mode=0640
- name: Set timezone in /etc/timezone
  copy: src=timezone dest=/etc/timezone
- name: Update timezone
  command: dpkg-reconfigure --frontend noninteractive tzdata
# TODO: Use special_time (or at least look at using it)
- name: Setting daily cron job for 10:00am
  cron: name="daily scraping" hour=10 minute=0 user=deploy job="cd /var/www/current && /home/deploy/.rvm/bin/rvm . do bundle exec rake app:auto_run_scrapers RAILS_ENV=production"
- name: Install nodejs for asset precompiling
  apt: pkg=nodejs
