---
- name: Ensure curl is installed
  apt: pkg=curl
- name: Ensure rvm installed in deploy user
  shell: curl -sSL https://get.rvm.io | bash -s stable creates=/home/deploy/.rvm
  sudo_user: deploy
# TODO: Is it possible to extract this list of dependencies automatically from rvm?
# Or allow rvm to do the install - but that would require the deploy user to have the permissions
- name: "Ensure ruby-2.0.0-p353 dependencies installed"
  apt: pkg={{ item }}
  with_items:
    - patch
    - gawk
    - g++
    - make
    - patch
    - libyaml-dev
    - libsqlite3-dev
    - sqlite3
    - autoconf
    - libgdbm-dev
    - libncurses5-dev
    - automake
    - libtool
    - bison
    - pkg-config
    - libffi-dev
- name: Ensure ruby-2.0.0-p353 is installed through rvm
  command: /bin/sh -l -c 'rvm install ruby-2.0.0-p353 --autolibs=read-fail' creates=/home/deploy/.rvm/rubies/ruby-2.0.0-p353
  sudo_user: deploy