# Faye
production:
  server: "https://faye.{{ server_name }}/faye"
  adapter_javascript_url: "https://faye.{{ server_name }}/faye/faye.js"
  adapter: "Faye"
  # auth_token is set to the environment variable SYNC_AUTH_TOKEN in sync.ru
  async: true
