---
# - name: Restart Apache
#   service: name=apache2 state=restarted
- name: restart nginx
  service: name=nginx state=restarted
- name: Update timezone
  command: dpkg-reconfigure --frontend noninteractive tzdata
- name: Test sudoers and make it live
  shell: visudo -c -f /etc/sudoers.d/deploy.test && cp -f /etc/sudoers.d/deploy.test /etc/sudoers.d/deploy
- name: Export to upstart
  command: foreman export upstart /etc/init -u deploy -a morph -f /home/deploy/Procfile.production --root /var/www/current
  notify: Restart morph service
- name: Restart morph service
  service: name=morph state=restarted
