---
- hosts: all
  sudo: true
# Uncomment the user line below if you are using this playbook directly from ansible using "ansible-playbook"
# rather than running it through vagrant
#  user: ubuntu
  roles:
    - docker-server
    - apache-passenger
    - ruby-2.0.0-p353
    - mysql
    - scraping-platform-app
    