---
- name: Ensure Apache is installed
  apt: pkg=apache2 update_cache=yes cache_valid_time=3600
- name: Ensure we have the Passenger key added
  apt_key: url=http://keyserver.ubuntu.com/pks/lookup?op=get&search=0x561F9B9CAC40B2F7 id=AC40B2F7
- name: Ensure we have HTTPS support for APT
  apt: pkg=apt-transport-https
- name: Ensure we have the passenger repository
  apt_repository: repo='deb https://oss-binaries.phusionpassenger.com/apt/passenger precise main'
- name: Ensure that passenger is installed
  apt: pkg=libapache2-mod-passenger
